FROM python:slim-buster
RUN apt-get update -y && \
    apt-get install -y && \
    pip install --upgrade pip && \
    pip install webexteamssdk pika redis requests configparser psycopg2-binary pymongo pytz 
