FROM python:slim-buster
RUN apt-get update -y && \
    apt-get install -y && \
    pip install flask configparser psycopg2-binary Flask-SQLAlchemy Flask-Migrate flask-cors pyOpenSSL pymongo Flask-PyMongo pandas matplotlib
